nodes:
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.ZarrDatasetNodes
      dataset: ./dataset.zarr
    attributes:
      area_weight:
        _target_: anemoi.graphs.nodes.attributes.AreaWeights
        norm: l2
