defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- hardware: slurm
- graph: multi_scale
- model: gnn
- training: default
- _self_


dataloader:
  training:
    start: 2017
    end: 2017
  validation:
    start: 2017
    end: 2017
  test:
    start: 2017
    end: 2017

hardware:
  num_gpus_per_model: 1
  paths:
    output: /pscratch/sd/t/timothys/aneml/nested-conus/era5-1.00/training-output/
    data: /pscratch/sd/t/timothys/aneml/nested-conus/era5-1.00/
    graph: /pscratch/sd/t/timothys/aneml/nested-conus/era5-1.00/
  files:
    dataset: 1year.zarr
    graph: multi_scale_graph.pt

training:
  max_steps: 1_000
